[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
base = "https://base-sepolia-rpc.publicnode.com"
# bnb = "https://bsc-testnet-dataseed.bnbchain.org"
# arbitrum = "https://sepolia-rollup.arbitrum.io/rpc"
# optimism = "https://sepolia.optimism.io"
# polygon = "https://rpc-amoy.polygon.technology/"
# zksync = "https://sepolia.era.zksync.dev"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
